name: Build and test RTCV
on: [push, pull_request]

jobs:
  buildAndTest:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Restore packages
      run: msbuild RTCV.sln /t:restore
    - name: Build with MSBuild
      run: msbuild RTCV.sln
    - name: Run tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Report coverage to codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        file: Tests/coverage.opencover.xml
