name: Report Code Coverage to CodeCov
on: [push]

jobs:
  coverage:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Restore packages
      run: msbuild RTCV.sln /t:restore
    - name: Build with MSBuild
      run: msbuild RTCV.sln
    - name: Run tests with coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Report coverage to codecov
      uses: codecov/codecov-action@master
      with:
        file: Tests/coverage.opencover.xml
